include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_relative_lib_imports: true
    eol_at_end_of_file: true
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
