name: Test Package

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup Stylizer
        run: mkdir tools && curl https://github.com/gmlewis/go-flutter-stylizer/releases/download/v0.1.7/flutter-stylizer-for-linux -Lo tools/flutter-stylizer && chmod +x tools/flutter-stylizer
      - run: flutter pub get
      - run: tools/flutter-stylizer --config .flutter-stylizer.yaml -l -w lib/... -w test/... -w storybook/...
      - run: flutter analyze
      - run: flutter test --coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov*.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
